//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table{
        ///				border-width:1px;
        ///				text-align:center;
        ///				border-color:#a9c6c9;
        ///				border-collapse:collapse;
        ///				border-style:solid;
        ///				background-color:#d4e3e5;
        ///				font-family:Verdana,Geneva,sans-serif;
        ///				font-size:11px;
        ///				color:teal
        ///}
        ///table th {
        ///				background-color:#c3dde0;
        ///				border-width: 1px;
        ///				padding: 5px;
        ///				border-style: solid;
        ///				border-color: #a9c6c9;
        ///}
        ///table tr {
        ///				background-color:#d4e3e5;
        ///}
        ///table td {
        ///				border-width: 1px;
        ///				padding: 3px;
        ///				border-styl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;style&gt; body {  font-family: &quot;Calibri&quot;,&quot;Slate Pro&quot;,&quot;sans-serif&quot;; color:#262626 }&lt;/style&gt; &lt;/head&gt; &lt;body data-blackberry-caret-color=&quot;#00a8df&quot; style=&quot;&quot;&gt;&lt;div&gt;â€$tc$&lt;span style=&quot;background-color: rgb(255, 255, 255); color: rgb(84, 84, 84); font-family: Arial, Helvetica, sans-serif; font-size: 12px;&quot;&gt;40579414082$&lt;/span&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Sent from my BlackBerry 10 smartphone.&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string htmlOne {
            get {
                return ResourceManager.GetString("htmlOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.ipinfodb.com/v3/ip-city/?key=84ff9ea6a5a542f9da2886b5cc2fe0f0bdfac8b624c6590bc1ad91223516cea0&amp;ip={0}.
        /// </summary>
        internal static string StringExtensions_GeoLocationUrl {
            get {
                return ResourceManager.GetString("StringExtensions_GeoLocationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3EsywndGe47Q.
        /// </summary>
        internal static string StringExtensions_OneWayHash__Salt {
            get {
                return ResourceManager.GetString("StringExtensions_OneWayHash__Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numaranız Sms Alımına Kapalı.Detaylı bilgi için operatorünüzle görüşünüz....
        /// </summary>
        internal static string StringExtensions_SendSms_Numaranız_Sms_Alımına_Kapalı_Detaylı_bilgi_için_operatorünüzle_görüşünüz___ {
            get {
                return ResourceManager.GetString("StringExtensions_SendSms_Numaranız_Sms_Alımına_Kapalı_Detaylı_bilgi_için_operator" +
                        "ünüzle_görüşünüz___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatörde sms gonderimi ile ilgili bir sorun olustu.Lütfen daha sonra tekrar deneyiniz....
        /// </summary>
        internal static string StringExtensions_SendSms_Operatörde_sms_gonderimi_ile_ilgili_bir_sorun_olustu_Lütfen_daha_sonra_tekrar_deneyiniz___ {
            get {
                return ResourceManager.GetString("StringExtensions_SendSms_Operatörde_sms_gonderimi_ile_ilgili_bir_sorun_olustu_Lüt" +
                        "fen_daha_sonra_tekrar_deneyiniz___", resourceCulture);
            }
        }
    }
}
